[CI]: improve logs and node setup

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,12 +5,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
       - uses: pnpm/action-setup@v2
         with:
           version: 9
       - name: Install
-        run: pnpm install --frozen-lockfile
+        run: pnpm install --frozen-lockfile --reporter=ndjson
       - name: Test
-        run: pnpm test --if-present
+        run: pnpm test --if-present || (echo "Tests failed" && exit 1)
       - name: Build
-        run: pnpm build --if-present
+        run: pnpm build --if-present || (echo "Build failed" && exit 1)
